"""secinfra-onboard — drop compliance workflow files into a local repo.

Creates (or updates) two files in the target repository:
  .github/workflows/compliance.yml   — calls the three reusable workflows
  .security/config.yml               — team email + ecosystem config

Usage examples
--------------
# Onboard a single repo interactively:
    secinfra-onboard --repo ../ignite-email-service

# Fully automated (no prompts):
    secinfra-onboard --repo ../ignite-email-service \\
        --email platform@ignitesol.com \\
        --systems security,licenses,bumblebee \\
        --ecosystems npm,python \\
        --ref v1

# Preview files without writing:
    secinfra-onboard --repo ../ignite-email-service --email x@ignitesol.com --dry-run

# Create a branch + commit (ready to push / open PR):
    secinfra-onboard --repo ../ignite-email-service --email x@ignitesol.com --branch

# Create a branch, commit, AND open a GitHub PR (requires gh CLI):
    secinfra-onboard --repo ../ignite-email-service --email x@ignitesol.com --open-pr

# Scan a workspace directory to see which repos are already onboarded:
    secinfra-onboard --scan-workspace ~/workspace
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import textwrap
from pathlib import Path

# ── constants ──────────────────────────────────────────────────────────────────

INFRA_REPO = "ignitesol/ignitesol.security-infra"
DEFAULT_REF = "main"          # bump to v1 after tagging
DEFAULT_BRANCH = "secinfra/compliance-setup"
COMPLIANCE_WORKFLOW = ".github/workflows/compliance.yml"
SECURITY_CONFIG = ".security/config.yml"

ALL_SYSTEMS = ["security", "licenses", "bumblebee"]
ALL_ECOSYSTEMS = ["npm", "python", "java"]

# Markers that mean a repo already has the compliance workflow
_ONBOARD_MARKERS = [
    "ignitesol.security-infra",
    "security-scan.yml",
    "license-tracker.yml",
]

# ── ecosystem detection ────────────────────────────────────────────────────────

_ECOSYSTEM_SIGNALS: dict[str, list[str]] = {
    "npm":    ["package.json"],
    "python": ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt", "poetry.lock"],
    "java":   ["pom.xml", "build.gradle", "build.gradle.kts"],
}


def detect_ecosystems(repo: Path) -> list[str]:
    found = []
    for eco, signals in _ECOSYSTEM_SIGNALS.items():
        if any((repo / s).exists() for s in signals):
            found.append(eco)
    return found or ["npm"]   # sane fallback


# ── remote detection ──────────────────────────────────────────────────────────

def _git_remote_slug(repo: Path) -> str:
    """Return 'org/repo' from the git remote, or empty string."""
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            cwd=str(repo), stderr=subprocess.DEVNULL,
        ).decode().strip()
        # https://github.com/org/repo.git  or  git@github.com:org/repo.git
        m = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", url)
        return m.group(1) if m else ""
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def _repo_name(repo: Path) -> str:
    slug = _git_remote_slug(repo)
    return slug.split("/")[-1] if slug else repo.name


def _default_branch(repo: Path) -> str:
    """Best-effort default branch detection (main / master)."""
    try:
        out = subprocess.check_output(
            ["git", "symbolic-ref", "--short", "HEAD"],
            cwd=str(repo), stderr=subprocess.DEVNULL,
        ).decode().strip()
        return out or "main"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "main"


# ── template rendering ────────────────────────────────────────────────────────

def _render_compliance_workflow(
    systems: list[str],
    ref: str,
    ecosystems: list[str],
    schedule: str | None,
) -> str:
    lines: list[str] = [
        f"# Compliance workflows for this repo — auto-generated by secinfra-onboard.",
        f"# Docs: https://github.com/{INFRA_REPO}",
        f"# Adjust triggers, systems, and ecosystems as needed.",
        "",
        "name: Compliance",
        "",
        "on:",
        "  push:",
        "    branches: [main]",
        "  workflow_dispatch:",
    ]
    if schedule:
        lines += [
            "  schedule:",
            f"    - cron: '{schedule}'",
        ]
    lines += [
        "",
        "permissions:",
        "  contents: write        # System 3 persists dependency manifest to state branch",
        "  id-token: write        # OIDC → SES in the notify jobs",
        "  security-events: write # System 1 uploads SARIF to GitHub Code Scanning",
        "",
        "jobs:",
    ]

    if "security" in systems:
        lines += [
            "  security:",
            f"    uses: {INFRA_REPO}/.github/workflows/security-scan.yml@{ref}",
            "    secrets: inherit",
            "    # with:",
            "    #   scan_root: src/          # default: .",
            "    #   semgrep_rules: p/python  # override central rules",
            "",
        ]

    if "licenses" in systems:
        eco_str = ",".join(e for e in ALL_ECOSYSTEMS if e in ecosystems)
        lines += [
            "  licenses:",
            f"    uses: {INFRA_REPO}/.github/workflows/license-tracker.yml@{ref}",
            "    secrets: inherit",
            "    with:",
            f'      ecosystems: "{eco_str}"',
            "    # Detected from your repo layout — adjust if needed.",
            "",
        ]

    if "bumblebee" in systems:
        lines += [
            "  bumblebee:",
            f"    uses: {INFRA_REPO}/.github/workflows/bumblebee-scan.yml@{ref}",
            "    secrets: inherit",
            "    # with:",
            "    #   scan_profile: project    # baseline | project | deep",
            "",
        ]

    return "\n".join(lines) + "\n"


def _render_security_config(
    email: str,
    ecosystems: list[str],
    systems: list[str],
) -> str:
    eco_lines = "\n".join(f"    - {e}" for e in ecosystems)
    sys_security  = str("security"  in systems).lower()
    sys_bumblebee = str("bumblebee" in systems).lower()
    sys_license   = str("licenses"  in systems).lower()

    return textwrap.dedent(f"""\
        # Security / compliance configuration for this repo.
        # Generated by secinfra-onboard.
        # Full reference: https://github.com/{INFRA_REPO}/blob/main/examples/security-config.yml

        email:
          to:
            - {email}

        systems:
          security: {sys_security}
          bumblebee: {sys_bumblebee}
          license: {sys_license}

        license:
          ecosystems:
        {eco_lines}

          # Optional: override the install command per ecosystem
          # install:
          #   npm: "npm ci --ignore-scripts"
          #   python: "pip install -r requirements.txt"
          #   java: "mvn -q dependency:resolve"

        paths:
          scan_root: "."
    """)


# ── onboarding status ─────────────────────────────────────────────────────────

def _is_onboarded(repo: Path) -> bool:
    wf = repo / COMPLIANCE_WORKFLOW
    if not wf.exists():
        return False
    content = wf.read_text()
    return any(m in content for m in _ONBOARD_MARKERS)


def _has_security_config(repo: Path) -> bool:
    return (repo / SECURITY_CONFIG).exists()


# ── workspace scan ────────────────────────────────────────────────────────────

def cmd_scan_workspace(workspace: Path) -> None:
    """Print a status table for every git repo under workspace."""
    repos = sorted(
        p for p in workspace.iterdir()
        if p.is_dir() and (p / ".git").exists()
    )
    if not repos:
        print(f"No git repos found under {workspace}")
        return

    # Header
    col_w = max(len(r.name) for r in repos) + 2
    print(f"\n{'REPO':<{col_w}}  {'COMPLIANCE':<12}  {'CONFIG':<8}  {'ECOSYSTEMS'}")
    print("-" * (col_w + 40))

    for repo in repos:
        onboarded = _is_onboarded(repo)
        has_cfg   = _has_security_config(repo)
        ecos      = detect_ecosystems(repo)
        status    = "✓ onboarded" if onboarded else "— missing"
        cfg_sym   = "✓" if has_cfg else "—"
        eco_str   = ", ".join(ecos)
        print(f"{repo.name:<{col_w}}  {status:<12}  {cfg_sym:<8}  {eco_str}")

    total = len(repos)
    done  = sum(1 for r in repos if _is_onboarded(r))
    print(f"\n{done}/{total} repos onboarded.\n")


# ── single-repo onboarding ────────────────────────────────────────────────────

def _prompt(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{question}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(1)
    return val or default


def cmd_onboard(args: argparse.Namespace) -> int:
    repo = Path(args.repo).expanduser().resolve()
    if not repo.exists():
        print(f"ERROR: repo path does not exist: {repo}", file=sys.stderr)
        return 1
    if not (repo / ".git").exists():
        print(f"ERROR: {repo} is not a git repository.", file=sys.stderr)
        return 1

    name   = _repo_name(repo)
    slug   = _git_remote_slug(repo)
    print(f"\n  Repo       : {name}" + (f"  ({slug})" if slug else ""))

    # ── resolve email ────────────────────────────────────────────────────────
    email: str = args.email or ""
    if not email:
        email = _prompt("  Team email (to:)", f"team-{name}@ignitesol.com")
    print(f"  Email  : {email}")

    # ── resolve ecosystems ───────────────────────────────────────────────────
    if args.ecosystems:
        ecosystems = [e.strip() for e in args.ecosystems.split(",") if e.strip()]
    else:
        ecosystems = detect_ecosystems(repo)
        print(f"  Ecosystems detected : {', '.join(ecosystems)}")
        if not args.yes:
            override = _prompt(
                "  Override ecosystems (comma-sep, or Enter to accept)",
                ",".join(ecosystems),
            )
            ecosystems = [e.strip() for e in override.split(",") if e.strip()]
    print(f"  Ecosystems : {', '.join(ecosystems)}")

    # ── resolve systems ──────────────────────────────────────────────────────
    if args.systems:
        systems = [s.strip() for s in args.systems.split(",") if s.strip()]
    else:
        systems = list(ALL_SYSTEMS)
    print(f"  Systems    : {', '.join(systems)}")

    ref      = args.ref or DEFAULT_REF
    schedule = args.schedule or None

    # ── render ───────────────────────────────────────────────────────────────
    workflow_content = _render_compliance_workflow(systems, ref, ecosystems, schedule)
    config_content   = _render_security_config(email, ecosystems, systems)

    workflow_path = repo / COMPLIANCE_WORKFLOW
    config_path   = repo / SECURITY_CONFIG

    if workflow_path.exists() and not args.force:
        print(f"\n  WARN: {COMPLIANCE_WORKFLOW} already exists. "
              "Use --force to overwrite.", file=sys.stderr)
        return 1

    # ── dry-run: just print ──────────────────────────────────────────────────
    if args.dry_run:
        _banner(f"DRY RUN — {COMPLIANCE_WORKFLOW}")
        print(workflow_content)
        _banner(f"DRY RUN — {SECURITY_CONFIG}")
        print(config_content)
        return 0

    # ── optionally switch to a new branch ────────────────────────────────────
    created_branch: str | None = None
    if args.open_pr or args.branch:
        branch_name = args.branch_name or DEFAULT_BRANCH
        _run_git(repo, ["checkout", "-b", branch_name])
        created_branch = branch_name
        print(f"\n  Branch : {branch_name}")

    # ── write files ──────────────────────────────────────────────────────────
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    workflow_path.write_text(workflow_content)
    config_path.write_text(config_content)
    print(f"\n  Written: {COMPLIANCE_WORKFLOW}")
    print(f"  Written: {SECURITY_CONFIG}")

    # ── commit if branching ───────────────────────────────────────────────────
    if created_branch:
        _run_git(repo, ["add", COMPLIANCE_WORKFLOW, SECURITY_CONFIG])
        _run_git(repo, [
            "commit", "-m",
            f"chore(secinfra): add compliance workflow and security config\n\n"
            f"Auto-generated by secinfra-onboard.\n"
            f"Ecosystems: {', '.join(ecosystems)}\n"
            f"Systems: {', '.join(systems)}",
        ])
        print(f"  Committed to branch: {created_branch}")

    # ── open PR ───────────────────────────────────────────────────────────────
    if args.open_pr:
        default_br = _default_branch(repo)
        pr_body = (
            f"## secinfra compliance onboarding\n\n"
            f"Auto-generated by `secinfra-onboard`.\n\n"
            f"**Systems enabled:** {', '.join(systems)}\n"
            f"**Ecosystems:** {', '.join(ecosystems)}\n\n"
            f"### Required org secrets (set at org level — no action needed):\n"
            f"- `SECINFRA_SES_ROLE_ARN`\n"
            f"- `SECINFRA_SES_FROM`\n"
            f"- `SECINFRA_SES_REGION`\n"
            f"- `SECINFRA_SECURITY_CC`\n\n"
            f"### After merge:\n"
            f"1. The first workflow run will send a baseline email to `{email}`.\n"
            f"2. The License Tracker will create the `secinfra/manifests` state branch automatically.\n\n"
            f"🤖 Generated with [secinfra-onboard](https://github.com/{INFRA_REPO})"
        )
        try:
            result = subprocess.run(
                ["gh", "pr", "create",
                 "--title", f"chore(secinfra): add compliance workflow",
                 "--body", pr_body,
                 "--base", default_br,
                 "--head", created_branch],
                cwd=str(repo), capture_output=True, text=True,
            )
            if result.returncode == 0:
                pr_url = result.stdout.strip()
                print(f"\n  PR     : {pr_url}")
            else:
                print(f"\n  WARN: gh pr create failed: {result.stderr.strip()}", file=sys.stderr)
                print("  You can open the PR manually after pushing the branch.")
        except FileNotFoundError:
            print("\n  WARN: `gh` CLI not found. Push the branch and open the PR manually.")

    if not created_branch:
        print(
            f"\n  Next steps:\n"
            f"    git -C {repo} add {COMPLIANCE_WORKFLOW} {SECURITY_CONFIG}\n"
            f"    git -C {repo} commit -m 'chore(secinfra): add compliance workflow'\n"
            f"    # then open a PR"
        )

    print()
    return 0


# ── helpers ───────────────────────────────────────────────────────────────────

def _banner(title: str) -> None:
    line = "─" * (len(title) + 4)
    print(f"\n┌{line}┐")
    print(f"│  {title}  │")
    print(f"└{line}┘\n")


def _run_git(repo: Path, cmd: list[str]) -> None:
    result = subprocess.run(
        ["git"] + cmd, cwd=str(repo),
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  git {' '.join(cmd)} failed:\n  {result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)


# ── CLI ───────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="secinfra-onboard",
        description="Onboard a repository to the IgniteSol security-infra compliance suite.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              secinfra-onboard --repo ../fizzy-metrics --email platform@ignitesol.com --open-pr
              secinfra-onboard --repo ../ignite-email-service --dry-run
              secinfra-onboard --scan-workspace ~/workspace
        """),
    )

    # ── mode flags ───────────────────────────────────────────────────────────
    mode = p.add_mutually_exclusive_group()
    mode.add_argument(
        "--scan-workspace", metavar="DIR",
        help="Print onboarding status for every git repo under DIR and exit.",
    )

    # ── target repo ──────────────────────────────────────────────────────────
    p.add_argument("--repo", metavar="PATH", default=".",
                   help="Path to the target repository (default: current directory).")

    # ── content options ──────────────────────────────────────────────────────
    p.add_argument("--email", metavar="ADDR",
                   help="Team email address for the to: field in .security/config.yml.")
    p.add_argument("--ecosystems", metavar="LIST",
                   help="Comma-separated ecosystems to enable: npm,python,java "
                        "(default: auto-detect from repo layout).")
    p.add_argument("--systems", metavar="LIST",
                   help="Comma-separated systems to enable: security,licenses,bumblebee "
                        f"(default: {','.join(ALL_SYSTEMS)}).")
    p.add_argument("--ref", metavar="REF", default=DEFAULT_REF,
                   help=f"Workflow ref/tag to pin (default: {DEFAULT_REF}).")
    p.add_argument("--schedule", metavar="CRON",
                   help="Optional cron expression to add a schedule trigger, "
                        "e.g. '0 6 * * *'.")

    # ── write mode ───────────────────────────────────────────────────────────
    p.add_argument("--dry-run", action="store_true",
                   help="Print the generated files without writing anything.")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing compliance.yml / config.yml if present.")
    p.add_argument("-y", "--yes", action="store_true",
                   help="Skip interactive prompts; use detected/provided values.")

    # ── branch / PR options ──────────────────────────────────────────────────
    branch_group = p.add_mutually_exclusive_group()
    branch_group.add_argument(
        "--branch", action="store_true",
        help="Create a new branch and commit the files (but don't push).",
    )
    branch_group.add_argument(
        "--open-pr", action="store_true",
        help="Create a branch, commit, push, and open a GitHub PR via gh CLI.",
    )
    p.add_argument("--branch-name", metavar="NAME", default=DEFAULT_BRANCH,
                   help=f"Branch name to use with --branch / --open-pr "
                        f"(default: {DEFAULT_BRANCH}).")

    return p


def main(argv: list[str] | None = None) -> int:
    p = _build_parser()
    args = p.parse_args(argv)

    if args.scan_workspace:
        cmd_scan_workspace(Path(args.scan_workspace).expanduser().resolve())
        return 0

    # If --open-pr we need to push; add that implicitly
    if args.open_pr:
        args.branch = True  # ensure branch creation path is taken

    return cmd_onboard(args)


if __name__ == "__main__":
    sys.exit(main())
